#!/bin/sh
# Author: Andreas Weber
# Date: 26.12.2006
# Purpose: Script to detect Nvidia Cards and assign a Driver

# Get Card info 
ID1=$(lspci -nn | grep "VGA\ compatible\ controller" | cut -d ' ' -f 1)
ID2=$(lspci -n | grep $ID1 | cut -d ' ' -f 3)
ID3=$(echo $ID2 | cut -d ':' -f 2 | tr '[a-z]' '[A-Z]')

case $ID3 in
# Detecting Cards which requires the legacy Driver
0020) NAME="RIVA TNT"; DRIVER="legacy"; AIGLX=0;;
0028) NAME="RIVA TNT2/TNT2 Pro"; DRIVER="legacy"; AIGLX=0;;
0029) NAME="RIVA TNT2 Ultra"; DRIVER="legacy"; AIGLX=0;;
00A0) NAME="Aladdin TNT2"; DRIVER="legacy"; AIGLX=0;;
002D) NAME="RIVA TNT2 Model 64/Model 64 Pro"; DRIVER="legacy"; AIGLX=0;;
0100) NAME="GeForce 256"; DRIVER="legacy"; AIGLX=0;;
0101) NAME="GeForce DDR"; DRIVER="legacy"; AIGLX=0;;
0110) NAME="GeForce2 MX/MX 400"; DRIVER="legacy"; AIGLX=0;;
0111) NAME="GeForce2 MX 100/200"; DRIVER="legacy"; AIGLX=0;;
0112) NAME="GeForce2 Go"; DRIVER="legacy"; AIGLX=0;;
0151) NAME="GeForce2 Ti"; DRIVER="legacy"; AIGLX=0;;
0152) NAME="GeForce2 Ultra"; DRIVER="legacy"; AIGLX=0;;
002C) NAME="Vanta/Vanta LT"; DRIVER="legacy"; AIGLX=0;;
0103) NAME="Quadro"; DRIVER="legacy"; AIGLX=0;;
0113) NAME="Quadro2 MXR/EX/Go"; DRIVER="legacy"; AIGLX=0;;
0150) NAME="GeForce2 GTS/GeForce2 Pro"; DRIVER="legacy"; AIGLX=0;;
0153) NAME="Quadro2 Pro"; DRIVER="legacy"; AIGLX=0;;

# Detecting Cards which are supported by the binary NVIDIA Driver
0112) NAME="GeForce2 Go"; DRIVER="nvidia"; AIGLX=0;;
01A0) NAME="GeForce2 Integrated GPU"; DRIVER="nvidia"; AIGLX=0;;
0111) NAME="GeForce2 MX 100/200"; DRIVER="nvidia"; AIGLX=0;;
0110) NAME="GeForce2 MX/MX 400"; DRIVER="nvidia"; AIGLX=0;;
0200) NAME="GeForce3"; DRIVER="nvidia"; AIGLX=0;;
0201) NAME="GeForce3 Ti 200"; DRIVER="nvidia"; AIGLX=0;;
0202) NAME="GeForce3 Ti 500"; DRIVER="nvidia"; AIGLX=0;;
017D) NAME="GeForce4 410 Go 16M"; DRIVER="nvidia"; AIGLX=0;;
0286) NAME="GeForce4 4200 Go"; DRIVER="nvidia"; AIGLX=0;;
0175) NAME="GeForce4 420 Go"; DRIVER="nvidia"; AIGLX=0;;
0176) NAME="GeForce4 420 Go 32M"; DRIVER="nvidia"; AIGLX=0;;
0174) NAME="GeForce4 440 Go"; DRIVER="nvidia"; AIGLX=0;;
0179) NAME="GeForce4 440 Go 64M"; DRIVER="nvidia"; AIGLX=0;;
0177) NAME="GeForce4 460 Go"; DRIVER="nvidia"; AIGLX=0;;
0185) NAME="GeForce4 MX 4000"; DRIVER="nvidia"; AIGLX=0;;
0172) NAME="GeForce4 MX 420"; DRIVER="nvidia"; AIGLX=0;;
0183) NAME="GeForce4 MX 420 with AGP8X"; DRIVER="nvidia"; AIGLX=0;;
0171) NAME="GeForce4 MX 440"; DRIVER="nvidia"; AIGLX=0;;
0173) NAME="GeForce4 MX 440-SE"; DRIVER="nvidia"; AIGLX=0;;
0182) NAME="GeForce4 MX 440SE with AGP8X"; DRIVER="nvidia"; AIGLX=0;;
0181) NAME="GeForce4 MX 440 with AGP8X"; DRIVER="nvidia"; AIGLX=0;;
0170) NAME="GeForce4 MX 460"; DRIVER="nvidia"; AIGLX=0;;
01F0) NAME="GeForce4 MX Integrated GPU"; DRIVER="nvidia"; AIGLX=0;;
0253) NAME="GeForce4 Ti 4200"; DRIVER="nvidia"; AIGLX=0;;
0281) NAME="GeForce4 Ti 4200 with AGP8X"; DRIVER="nvidia"; AIGLX=0;;
0251) NAME="GeForce4 Ti 4400"; DRIVER="nvidia"; AIGLX=0;;
0250) NAME="GeForce4 Ti 4600"; DRIVER="nvidia"; AIGLX=0;;
0280) NAME="GeForce4 Ti 4800"; DRIVER="nvidia"; AIGLX=0;;
0282) NAME="GeForce4 Ti 4800 SE"; DRIVER="nvidia"; AIGLX=0;;
0242) NAME="GeForce 6100"; DRIVER="nvidia"; AIGLX=1;;
0240) NAME="GeForce 6150"; DRIVER="nvidia"; AIGLX=1;;
0241) NAME="GeForce 6150 LE"; DRIVER="nvidia"; AIGLX=1;;
00F3) NAME="GeForce 6200"; DRIVER="nvidia"; AIGLX=1;;
014F) NAME="GeForce 6200"; DRIVER="nvidia"; AIGLX=1;;
0163) NAME="GeForce 6200 LE"; DRIVER="nvidia"; AIGLX=1;;
0161) NAME="GeForce 6200 TurboCache™"; DRIVER="nvidia"; AIGLX=1;;
0160) NAME="GeForce 6500"; DRIVER="nvidia"; AIGLX=1;;
00F2) NAME="GeForce 6600"; DRIVER="nvidia"; AIGLX=1;;
0141) NAME="GeForce 6600"; DRIVER="nvidia"; AIGLX=1;;
00F1) NAME="GeForce 6600/GeForce 6600 GT"; DRIVER="nvidia"; AIGLX=1;;
0140) NAME="GeForce 6600 GT"; DRIVER="nvidia"; AIGLX=1;;
00F4) NAME="GeForce 6600 LE"; DRIVER="nvidia"; AIGLX=1;;
0142) NAME="GeForce 6600 LE"; DRIVER="nvidia"; AIGLX=1;;
0143) NAME="GeForce 6600 VE"; DRIVER="nvidia"; AIGLX=1;;
0145) NAME="GeForce 6610 XL"; DRIVER="nvidia"; AIGLX=1;;
0147) NAME="GeForce 6700 XL"; DRIVER="nvidia"; AIGLX=1;;
0041) NAME="GeForce 6800"; DRIVER="nvidia"; AIGLX=1;;
00C1) NAME="GeForce 6800"; DRIVER="nvidia"; AIGLX=1;;
0211) NAME="GeForce 6800"; DRIVER="nvidia"; AIGLX=1;;
00F0) NAME="GeForce 6800/GeForce 6800 Ultra"; DRIVER="nvidia"; AIGLX=1;;
0047) NAME="GeForce 6800 GS"; DRIVER="nvidia"; AIGLX=1;;
00C0) NAME="GeForce 6800 GS"; DRIVER="nvidia"; AIGLX=1;;
00F6) NAME="GeForce 6800 GS"; DRIVER="nvidia"; AIGLX=1;;
0045) NAME="GeForce 6800 GT"; DRIVER="nvidia"; AIGLX=1;;
0046) NAME="GeForce 6800 GT"; DRIVER="nvidia"; AIGLX=1;;
0215) NAME="GeForce 6800 GT"; DRIVER="nvidia"; AIGLX=1;;
00C2) NAME="GeForce 6800 LE"; DRIVER="nvidia"; AIGLX=1;;
0212) NAME="GeForce 6800 LE"; DRIVER="nvidia"; AIGLX=1;;
0040) NAME="GeForce 6800 Ultra"; DRIVER="nvidia"; AIGLX=1;;
00F9) NAME="GeForce 6800 Ultra"; DRIVER="nvidia"; AIGLX=1;;
0043) NAME="GeForce 6800 XE"; DRIVER="nvidia"; AIGLX=1;;
0044) NAME="GeForce 6800 XT"; DRIVER="nvidia"; AIGLX=1;;
0048) NAME="GeForce 6800 XT"; DRIVER="nvidia"; AIGLX=1;;
00C3) NAME="GeForce 6800 XT"; DRIVER="nvidia"; AIGLX=1;;
0218) NAME="GeForce 6800 XT"; DRIVER="nvidia"; AIGLX=1;;
01DF) NAME="GeForce 7300 GS"; DRIVER="nvidia"; AIGLX=1;;
0393) NAME="GeForce 7300 GT"; DRIVER="nvidia"; AIGLX=1;;
01D1) NAME="GeForce 7300 LE"; DRIVER="nvidia"; AIGLX=1;;
01D3) NAME="GeForce 7300 SE"; DRIVER="nvidia"; AIGLX=1;;
02E1) NAME="GeForce 7600 GS"; DRIVER="nvidia"; AIGLX=1;;
0392) NAME="GeForce 7600 GS"; DRIVER="nvidia"; AIGLX=1;;
0391) NAME="GeForce 7600 GT"; DRIVER="nvidia"; AIGLX=1;;
0093) NAME="GeForce 7800 GS"; DRIVER="nvidia"; AIGLX=1;;
00F5) NAME="GeForce 7800 GS"; DRIVER="nvidia"; AIGLX=1;;
0092) NAME="GeForce 7800 GT"; DRIVER="nvidia"; AIGLX=1;;
0090) NAME="GeForce 7800 GTX"; DRIVER="nvidia"; AIGLX=1;;
0091) NAME="GeForce 7800 GTX"; DRIVER="nvidia"; AIGLX=1;;
0090) NAME="GeForce 7800 GTX 512"; DRIVER="nvidia"; AIGLX=1;;
0292) NAME="GeForce 7900 GS"; DRIVER="nvidia"; AIGLX=1;;
0291) NAME="GeForce 7900 GT"; DRIVER="nvidia"; AIGLX=1;;
0290) NAME="GeForce 7900 GTX"; DRIVER="nvidia"; AIGLX=1;;
0294) NAME="GeForce 7950 GX2"; DRIVER="nvidia"; AIGLX=1;;
0327) NAME="GeForce FX 5100"; DRIVER="nvidia"; AIGLX=1;;
0320) NAME="GeForce FX 5200"; DRIVER="nvidia"; AIGLX=1;;
0322) NAME="GeForce FX 5200"; DRIVER="nvidia"; AIGLX=1;;
0323) NAME="GeForce FX 5200LE"; DRIVER="nvidia"; AIGLX=1;;
0321) NAME="GeForce FX 5200 Ultra"; DRIVER="nvidia"; AIGLX=1;;
0326) NAME="GeForce FX 5500"; DRIVER="nvidia"; AIGLX=1;;
0312) NAME="GeForce FX 5600"; DRIVER="nvidia"; AIGLX=1;;
0311) NAME="GeForce FX 5600 Ultra"; DRIVER="nvidia"; AIGLX=1;;
0314) NAME="GeForce FX 5600XT"; DRIVER="nvidia"; AIGLX=1;;
0342) NAME="GeForce FX 5700"; DRIVER="nvidia"; AIGLX=1;;
0343) NAME="GeForce FX 5700LE"; DRIVER="nvidia"; AIGLX=1;;
0341) NAME="GeForce FX 5700 Ultra"; DRIVER="nvidia"; AIGLX=1;;
0344) NAME="GeForce FX 5700VE"; DRIVER="nvidia"; AIGLX=1;;
0302) NAME="GeForce FX 5800"; DRIVER="nvidia"; AIGLX=1;;
0301) NAME="GeForce FX 5800 Ultra"; DRIVER="nvidia"; AIGLX=1;;
0331) NAME="GeForce FX 5900"; DRIVER="nvidia"; AIGLX=1;;
0330) NAME="GeForce FX 5900 Ultra"; DRIVER="nvidia"; AIGLX=1;;
0332) NAME="GeForce FX 5900XT"; DRIVER="nvidia"; AIGLX=1;;
0334) NAME="GeForce FX 5900ZT"; DRIVER="nvidia"; AIGLX=1;;
0333) NAME="GeForce FX 5950 Ultra"; DRIVER="nvidia"; AIGLX=1;;
032D) NAME="GeForce FX Go5100"; DRIVER="nvidia"; AIGLX=1;;
0324) NAME="GeForce FX Go5200"; DRIVER="nvidia"; AIGLX=1;;
0328) NAME="GeForce FX Go5200 32M/64M"; DRIVER="nvidia"; AIGLX=1;;
0325) NAME="GeForce FX Go5250"; DRIVER="nvidia"; AIGLX=1;;
032C) NAME="GeForce FX Go53xx"; DRIVER="nvidia"; AIGLX=1;;
031A) NAME="GeForce FX Go5600"; DRIVER="nvidia"; AIGLX=1;;
031B) NAME="GeForce FX Go5650"; DRIVER="nvidia"; AIGLX=1;;
0347) NAME="GeForce FX Go5700"; DRIVER="nvidia"; AIGLX=1;;
0348) NAME="GeForce FX Go5700"; DRIVER="nvidia"; AIGLX=1;;
0164) NAME="GeForce Go 6200"; DRIVER="nvidia"; AIGLX=1;;
0167) NAME="GeForce Go 6200"; DRIVER="nvidia"; AIGLX=1;;
0166) NAME="GeForce Go 6400"; DRIVER="nvidia"; AIGLX=1;;
0168) NAME="GeForce Go 6400"; DRIVER="nvidia"; AIGLX=1;;
0144) NAME="GeForce Go 6600"; DRIVER="nvidia"; AIGLX=1;;
0148) NAME="GeForce Go 6600"; DRIVER="nvidia"; AIGLX=1;;
0149) NAME="GeForce Go 6600 GT"; DRIVER="nvidia"; AIGLX=1;;
0146) NAME="GeForce Go 6600 TE/6200 TE"; DRIVER="nvidia"; AIGLX=1;;
00C8) NAME="GeForce Go 6800"; DRIVER="nvidia"; AIGLX=1;;
00C9) NAME="GeForce Go 6800 Ultra"; DRIVER="nvidia"; AIGLX=1;;
01D7) NAME="GeForce Go 7300"; DRIVER="nvidia"; AIGLX=1;;
01D8) NAME="GeForce Go 7400"; DRIVER="nvidia"; AIGLX=1;;
0398) NAME="GeForce Go 7600"; DRIVER="nvidia"; AIGLX=1;;
0098) NAME="GeForce Go 7800"; DRIVER="nvidia"; AIGLX=1;;
0099) NAME="GeForce Go 7800 GTX"; DRIVER="nvidia"; AIGLX=1;;
0298) NAME="GeForce Go 7900 GS"; DRIVER="nvidia"; AIGLX=1;;
0299) NAME="GeForce Go 7900 GTX"; DRIVER="nvidia"; AIGLX=1;;
00FF) NAME="GeForce PCX 4300"; DRIVER="nvidia"; AIGLX=1;;
00FA) NAME="GeForce PCX 5750"; DRIVER="nvidia"; AIGLX=1;;
00FB) NAME="GeForce PCX 5900"; DRIVER="nvidia"; AIGLX=1;;
0113) NAME="Quadro2 MXR/EX/Go"; DRIVER="nvidia"; AIGLX=1;;
018B) NAME="Quadro4 380 XGL"; DRIVER="nvidia"; AIGLX=1;;
017C) NAME="Quadro4 500 GoGL"; DRIVER="nvidia"; AIGLX=1;;
0178) NAME="Quadro4 550 XGL"; DRIVER="nvidia"; AIGLX=1;;
0188) NAME="Quadro4 580 XGL"; DRIVER="nvidia"; AIGLX=1;;
028C) NAME="Quadro4 700 GoGL"; DRIVER="nvidia"; AIGLX=1;;
025B) NAME="Quadro4 700 XGL"; DRIVER="nvidia"; AIGLX=1;;
0259) NAME="Quadro4 750 XGL"; DRIVER="nvidia"; AIGLX=1;;
0289) NAME="Quadro4 780 XGL"; DRIVER="nvidia"; AIGLX=1;;
0258) NAME="Quadro4 900 XGL"; DRIVER="nvidia"; AIGLX=1;;
0288) NAME="Quadro4 980 XGL"; DRIVER="nvidia"; AIGLX=1;;
0203) NAME="Quadro DCC"; DRIVER="nvidia"; AIGLX=1;;
0309) NAME="Quadro FX 1000"; DRIVER="nvidia"; AIGLX=1;;
034E) NAME="Quadro FX 1100"; DRIVER="nvidia"; AIGLX=1;;
00FE) NAME="Quadro FX 1300"; DRIVER="nvidia"; AIGLX=1;;
00CE) NAME="Quadro FX 1400"; DRIVER="nvidia"; AIGLX=1;;
029E) NAME="Quadro FX 1500"; DRIVER="nvidia"; AIGLX=1;;
029B) NAME="Quadro FX 1500M"; DRIVER="nvidia"; AIGLX=1;;
0308) NAME="Quadro FX 2000"; DRIVER="nvidia"; AIGLX=1;;
029A) NAME="Quadro FX 2500M"; DRIVER="nvidia"; AIGLX=1;;
0338) NAME="Quadro FX 3000"; DRIVER="nvidia"; AIGLX=1;;
00FC) NAME="Quadro FX 330/GeForce PCX 5300"; DRIVER="nvidia"; AIGLX=1;;
00F8) NAME="Quadro FX 3400"; DRIVER="nvidia"; AIGLX=1;;
00CD) NAME="Quadro FX 3450/4000 SDI"; DRIVER="nvidia"; AIGLX=1;;
01DC) NAME="Quadro FX 350M"; DRIVER="nvidia"; AIGLX=1;;
029D) NAME="Quadro FX 3500"; DRIVER="nvidia"; AIGLX=1;;
004E) NAME="Quadro FX 4000"; DRIVER="nvidia"; AIGLX=1;;
00F8) NAME="Quadro FX 4400"; DRIVER="nvidia"; AIGLX=1;;
009D) NAME="Quadro FX 4500"; DRIVER="nvidia"; AIGLX=1;;
029F) NAME="Quadro FX 4500"; DRIVER="nvidia"; AIGLX=1;;
029F) NAME="Quadro FX 4500 X2"; DRIVER="nvidia"; AIGLX=1;;
029C) NAME="Quadro FX 5500"; DRIVER="nvidia"; AIGLX=1;;
01DE) NAME="Quadro FX 350"; DRIVER="nvidia"; AIGLX=1;;
032B) NAME="Quadro FX 500/600 PCI"; DRIVER="nvidia"; AIGLX=1;;
014E) NAME="Quadro FX 540"; DRIVER="nvidia"; AIGLX=1;;
014C) NAME="Quadro FX 550"; DRIVER="nvidia"; AIGLX=1;;
039E) NAME="Quadro FX 560"; DRIVER="nvidia"; AIGLX=1;;
033F) NAME="Quadro FX 700"; DRIVER="nvidia"; AIGLX=1;;
034C) NAME="Quadro FX Go1000"; DRIVER="nvidia"; AIGLX=1;;
00CC) NAME="Quadro FX Go1400"; DRIVER="nvidia"; AIGLX=1;;
031C) NAME="Quadro FX Go700"; DRIVER="nvidia"; AIGLX=1;;
017A) NAME="Quadro NVS"; DRIVER="nvidia"; AIGLX=1;;
01D7) NAME="Quadro NVS 110M"; DRIVER="nvidia"; AIGLX=1;;
01DA) NAME="Quadro NVS 110M"; DRIVER="nvidia"; AIGLX=1;;
01DB) NAME="Quadro NVS 120M"; DRIVER="nvidia"; AIGLX=1;;
032A) NAME="Quadro NVS 280 PCI"; DRIVER="nvidia"; AIGLX=1;;
00FD) NAME="Quadro NVS 280 PCI-E/Quadro FX 330"; DRIVER="nvidia"; AIGLX=1;;
0165) NAME="Quadro NVS 285"; DRIVER="nvidia"; AIGLX=1;;
014A) NAME="Quadro NVS 440"; DRIVER="nvidia"; AIGLX=1;;
018C) NAME="Quadro NVS 50 PCI"; DRIVER="nvidia"; AIGLX=1;;
018A) NAME="Quadro NVS with AGP8X"; DRIVER="nvidia"; AIGLX=1;;

# Unsupported Cards
0221) NAME="GeForce 6200"; DRIVER="ask"; AIGLX=0;;

*) NAME="Unknown NVIDIA Card"; DRIVER="nv"; AIGLX=0;;
esac

if [ $DRIVER = "ask" ]; then
	echo "Your Card isn't supported by the linux nvidia driver."
	echo ""
	DRIVER="nv"
fi

case $AIGLX in
	0) AIGLX="No"
	;;
	1) AIGLX="Yes"
	;;
esac

echo "Detected Card: $NAME"
echo "Driver: $DRIVER"
echo "PCI ID: $ID3"
echo "AIGLX Support: $AIGLX"

