Document: sidux-binary-gfx
Title: Debian sidux-binary-gfx Manual
Author: <insert document author here>
Abstract: This manual describes what sidux-binary-gfx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sidux-binary-gfx/sidux-binary-gfx.sgml.gz

Format: postscript
Files: /usr/share/doc/sidux-binary-gfx/sidux-binary-gfx.ps.gz

Format: text
Files: /usr/share/doc/sidux-binary-gfx/sidux-binary-gfx.text.gz

Format: HTML
Index: /usr/share/doc/sidux-binary-gfx/html/index.html
Files: /usr/share/doc/sidux-binary-gfx/html/*.html

  
